### PR TITLE
Run tests on GitHub Actions

### PR DESCRIPTION
**Pull request by sajith**
Addresses #13.  [Here](https://github.com/sajith/sdx-lc/runs/7755790576) is an example of this in action.

Note that tests are currently failing, and it is a bit of a chicken-and-egg problem. When we address the test failures, we should be able to run tests on CI in order verify that the fixes actually work.  Let us have a CI first, and then try to make tests pass on CI.

### CODE REVIEW

**Review by congwang09 — APPROVED** [review]
🚢

**Comment by lmarinve** [comment]
We do not need to test on python 3.5 to 3.8, only 3.9

**Comment by lmarinve** [comment]
Python 3.10 have very cool new stuff and performance, but in kytos we need a big change handling async; for now, we are formally focused on fixing all bugs in version 3.9

**Comment by sajith** [comment]
> Python 3.10 have very cool new stuff and performance, but in kytos we need a big change handling async; for now, we are formally focused on fixing all bugs in version 3.9

Other components that do not directly depend on Kytos can evolve independently, right?  My thinking is that we can try and make the tests pass with Python 3.10 where possible, especially if it is easy to do so.  At a minimum, it would be worthwhile to keep an eye on what happens when we run the code with Python 3.10.

**Comment by lmarinve** [comment]
Sure, it is good to test on Python 3.10, it is the future, but it has to work in Python 3.9 which is the current, cool!

**Pull request merged**
