### PR TITLE
Update env.template

### PR DESCRIPTION
**Pull request by congwang09**
Resolves: https://github.com/atlanticwave-sdx/sdx-lc/issues/87
Delete the old env, and add new env.template.

### CODE REVIEW

**Review by sajith — APPROVED** [review]
Might want to update `docker-compose.yml` also (similar to how it is done in SDX Controller) so that it picks up values from `.env`?

**Comment by congwang09** [comment]
> Might want to update `docker-compose.yml` also (similar to how it is done in SDX Controller) so that it picks up values from `.env`?

Yes true, updated docker-compose.yml as well. Requesting another look, just to make sure I didn't make mistakes.

**Comment by sajith** [comment]
I did a `source env.template && docker compose up --build`, but the app failed to run because the app did not wait for MongoDB service to become available.  It seems that we need this under `sdx-lc` service: 

```yaml
    depends_on:
      my-mongodb:
        condition: service_started
```

... and a `healthcheck` under `my-mongodb`:

```yaml
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ${MONGO_HOST}:${MONGO_PORT}/test --quiet
```

Also, `MONGO_HOST` should be `my-mongodb` service (docker networking name), not `localhost`.  This could be a change in env file or compose file. (In sdx-controller's compose file, I actually hard-coded the docker service name, because that almost always works reliably, and I don't have to change environment variables to run the test suite.)

With those changes, the service is up and running.  I haven't actually tested other things (like publishing a topology over the message queue), so I can't vouch for those things.

Couple of other recommendations:

- This might be a good time to switch to MongoDB 7.0.5, because 3.7.9 is too old and there are warnings about using it because it is considered a development version.  MongoDB 7.0.5 that is what we use in sdx-controller.  
- Also, in sdx-controller, `docker-compose.yml` has been renamed to just `compose.yml`, because that is the preferred name: https://docs.docker.com/compose/compose-application-model/.

@congwang09 I can't do another approval unless you request another review (there's a tiny little button on this page for that). Feel free to merge this now, if you want to. I can address the little issues in a follow-up.

**Comment by sajith** [comment]
Another suggestion is to use Docker volumes (https://docs.docker.com/storage/volumes/) for MongoDB persistence, which we use in sdx-controller, with something like the below in `compose.yml`:

```yaml
services:
  mongodb:
    volumes:
      - type: volume
        source: mongodb
        target: /data/db:Z

volumes:
  mongodb:
```

**Comment by congwang09** [comment]
> I did a `source env.template && docker compose up --build`, but the app failed to run because the app did not wait for MongoDB service to become available. It seems that we need this under `sdx-lc` service:
> 
> ```yaml
>     depends_on:
>       my-mongodb:
>         condition: service_started
> ```
> 
This part is very strange, this PR didn't change the dependencies. Is the main branch building correctly? If we do need the `depends_on` part, I'll do a separate PR. So if something goes wrong, we can simply revert the PR.

> ... and a `healthcheck` under `my-mongodb`:
> 
> ```yaml
>     healthcheck:
>       test: echo 'db.runCommand("ping").ok' | mongo ${MONGO_HOST}:${MONGO_PORT}/test --quiet
> ```
> 
> Also, `MONGO_HOST` should be `my-mongodb` service (docker networking name), not `localhost`. This could be a change in env file or compose file. (In sdx-controller's compose file, I actually hard-coded the docker service name, because that almost always works reliably, and I don't have to change environment variables to run the test suite.)

Sounds good. Updated.
> 
> With those changes, the service is up and running. I haven't actually tested other things (like publishing a topology over the message queue), so I can't vouch for those things.
> 
> Couple of other recommendations:
> 
> * This might be a good time to switch to MongoDB 7.0.5, because 3.7.9 is too old and there are warnings about using it because it is considered a development version.  MongoDB 7.0.5 that is what we use in sdx-controller.
> * Also, in sdx-controller, `docker-compose.yml` has been renamed to just `compose.yml`, because that is the preferred name: https://docs.docker.com/compose/compose-application-model/.
> 
This will also go into a separate PR, since it's different topic, so we can revert the PR if something goes wrong.

> @congwang09 I can't do another approval unless you request another review (there's a tiny little button on this page for that). Feel free to merge this now, if you want to. I can address the little issues in a follow-up.

I have requested another review (5 days ago), so there's no more "request review" button, but yeah this doesn't block merging.

**Review by sajith — APPROVED** [review]

**Comment by sajith** [comment]
`docker compose build` will work just fine, but chances are `docker compose up` will not.  If it did, it was likely connecting to an already-running MongoDB instance on localhost:27017, not the one brought up by compose.

**Comment by sajith** [comment]
Seems that the testbed LC hosts have MongoDB processes running on localhost. That should explain how it worked so far, I think.

In order to avoid confusion, we should also try not to expose MongoDB port outside of compose.

**Comment by sajith** [comment]
> I have requested another review (5 days ago), so there's no more "request review" button, but yeah this doesn't block merging.

In that case either I did not receive a notification, or I have failed in GitHub. Sorry!

I think we can go ahead and merge this now, and we can make other changes separately.  I would like to have the dependencies resolved, but even that could be a separate change. 

Also, we should stop any unintended/unused MongoDB process on the testbed.  I think testing things in a "cleaner" environment (locally or in a temporary VM) will help us catch these things, at least when in doubt.

**Comment by congwang09** [comment]
> > I have requested another review (5 days ago), so there's no more "request review" button, but yeah this doesn't block merging.
> 
> In that case either I did not receive a notification, or I have failed in GitHub. Sorry!
> 
No worries! I was just referring back to the request.

> I think we can go ahead and merge this now, and we can make other changes separately. I would like to have the dependencies resolved, but even that could be a separate change.
> 
Sounds good. I'm merging the PR for now. Will address the comments in the follow ups.

> Also, we should stop any unintended/unused MongoDB process on the testbed. I think testing things in a "cleaner" environment (locally or in a temporary VM) will help us catch these things, at least when in doubt.

Yes I'll double check that.

**Pull request merged**
