### PR TITLE
Make SDX Local Controller a WSGI app

### LINKED ISSUE #86: Use WSGI or ASGI
Similar to https://github.com/atlanticwave-sdx/sdx-controller/issues/135.

### PR DESCRIPTION
**Pull request by sajith**
Resolves #86.

### CODE REVIEW

**Review by YufengXin — APPROVED** [review]
ASGI vs WSGI;

Flask vs. uvicorn vs. gunicorn

FastAPI vs. swagger UI 

Please write a blog for educational purpose...

**Comment by sajith** [comment]
> ASGI vs WSGI;
> 
> Flask vs. uvicorn vs. gunicorn
> 
> FastAPI vs. swagger UI
> 
> Please write a blog for educational purpose...

@YufengXin Is that a request meant for me?

:see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by YufengXin** [comment]
@sajith Yes-:) I assume you're moving to upgrade sdx-controller too?
The justification on the choice would be nice to be included in the annual report.

**Comment by sajith** [comment]
This is already done on sdx-controller.

For production usage, using Flask's built-in web server directly is not a good idea, since it is single threaded and synchronous.  It is good enough during development, but it just not meant to be used in production.  It should be used in conjunction with a [WSGI](https://en.wikipedia.org/wiki/Web_Server_Gateway_Interface) server (Gunicorn, uWSGI),   since it is more secure, scalable, and can work with reverse proxy web servers (such as nginx or caddy, which we will need for SSL termination).

[ASGI](https://en.wikipedia.org/wiki/Asynchronous_Server_Gateway_Interface) is essentially the updated version of WSGI that understands `async`/`await`.  We are not quite there, but I liked [uvicorn](https://www.uvicorn.org/), which is an ASGI server, enough to make our app sort-of-ASGI with `WsgiToAsgi()` adaptor.  We can always switch to gunicorn or uWSGI or something else if we need to do so.

**Comment by YufengXin** [comment]
The first part is clear as we always do.

I don't know much about ASGI. So the key is the wsgi_to_asgi converter. as my naive understanding is that FASTAPI is to ASGI as Flask to WSGI. But somebody on Internet said Flask2.0 supports ASGI....

Nice upgrade. I'll read more into it.

**Comment by sajith** [comment]
FastAPI is an alternative to connexion and Flask, if I understood correctly.  It probably would be nicer too, but it is also very likely to come with its own set of limitations.

Since the choice has already been made, and since we're somewhat familiar with Flask and connexion, and since there is a cost (time and opportunity) to switching, I am of the opinion that we should continue working with the current setup.  Unless there is a good reason to switch to something else, of course. :-)

**Comment by sajith** [comment]
Also the `WsgiToAsgi()` call is really optional.  We can simply remove that line and use gunicorn instead of uvicorn and forget that we ever tried to use an ASGI server.

**Comment by YufengXin** [comment]
Totally agree. Let's keep it this way, because you made it work well-:)

**Comment by sajith** [comment]
Thank you.  There's more to be done, of course. :-)

**Pull request merged**
