### PR TITLE
Update flask-testing library

### PR DESCRIPTION
**Pull request by sajith**
This should address #15.

I expect that there will be other unrelated errors when running tests on CI.  I will try to address them separately.

### CODE REVIEW

**Comment by sajith** [comment]
Seems that we will need some more things in order to be able to run tests:

- Run RabbitMQ, probably using docker or podman.
- Set some environment variables, like the ones set in env file.
- Pass those environment variables to tox, with something like `passenv = SDX_* SDXLC_* MQ_* DB_*` under `[testenv]`.

Current status: I tried all that, and tests are still not passing.

**Comment by sajith** [comment]
Although tests are not passing, the error about missing `flask.json_available` is gone.

It probably would be a good idea to merge this now, just to limit the scope of this PR. I will investigate the rest of the test setup separately.

**Comment by lmarinve** [comment]
I updated the sdx-continuous-development using multipass and podman in ubuntu 22.04 virtual machine, we can try it now in this test environment

**Comment by sajith** [comment]
@lmarinve I believe that is a separate thing from this. :-)

With setting up GitHub Actions on individual repositories, I am trying to make sure that we have a CI story, such that tests are run _somewhere_ outside of developer machines.  The sdx-continuous-development repository, I believe, would be the CD part, where we pull in various pieces and test them together.  The CI part is a low-hanging fruit, and working on this gives me an opportunity to get somewhat familiar with the individual pieces.

**Comment by lmarinve** [comment]
@sajith, yes, you're right. Multipass is an ubuntu virtual machine where we can put all the pieces together with podman; we do not need to care about mac or windows. It is very easy to install on any computer. I just mentioned it to have it present when you thinking about:
Run RabbitMQ, probably using docker or podman.
Set some environment variables, like the ones set in env file.
Pass those environment variables to tox, with something like passenv = SDX_* SDXLC_* MQ_* DB_* under [testenv].

**Review by congwang09 — APPROVED** [review]
LGTM! 🚢

**Comment by sajith** [comment]
@lmarinve I am thinking about the CD part going on a testbed, at least in the beginning.

It would be certainly good to be able to test everything together outside of testbeds too.  But I am unsure about multipass.  I do not develop on macOS or Windows, and multipass isn't packaged for Debian or Fedora (which I use -- it is certainly possible to install multipass on them from sources but I will have to do that), so... don't know. :-)

Perhaps Vagrant would be an option there?  Vagrant is more widely available, and better understood. 

I have been told that you can have any distribution that supports cloud-init in multipass, but `multipass find` only lists Ubuntu images and some others that do not look relevant to us.  The RENCI test bed is all RHEL 8 equivalents, so if we want some level of equivalence between the setup on testbed and the setup on developer machines, would multipass limit us?  Or does it not matter, because things are in containers?

I understand that Vagrant's limitation is that VirtualBox isn't available on M1 Macs yet. People seem to be finding workarounds, but I don't know how well that would work.  So maybe Ubuntu in multipass would be useful there.

As for this repository's CI, it should be possible to run RabbitMQ in podman or docker.  l will find out.

**Comment by lmarinve** [comment]
Yes, you can install multipass in fedora and Debian with snapcraft, https://snapcraft.io/install/multipass/fedora, multipass only generate a virtual machine in ubuntu 18.04 with python 3.6, 20.04 with python 3.8 or 22.04 with python 3.10; after you have the virtual machine, you can use podman to generate any rhel 8 and Debian images for kytos and sdx-lc, server etc

**Pull request merged**
